export const importedProducts = [
  // Games - Minecraft
  {
    category: 'games',
    name: 'Starter',
    description: 'Entry-level gaming',
    price: '50',
    specs: { ram: '2GB DDR4 RAM', cpu: '1 vCore CPU', ssd: '4GB NVMe SSD' },
    display_order: 1,
  },
  {
    category: 'games',
    name: 'Performance',
    description: 'Smooth gameplay',
    price: '100',
    specs: { ram: '4GB DDR4 RAM', cpu: '150% CPU', ssd: '6GB NVMe SSD' },
    display_order: 2,
  },
  {
    category: 'games',
    name: 'Ultra Boost',
    description: 'Power players',
    price: '200',
    specs: { ram: '6GB DDR4 RAM', cpu: '200% CPU', ssd: '20GB NVMe SSD' },
    featured: true,
    badge: 'MOST POPULAR',
    display_order: 3,
  },
  {
    category: 'games',
    name: 'Pro Max',
    description: 'For communities',
    price: '350',
    specs: { ram: '8GB DDR4 RAM', cpu: '250% CPU', ssd: '30GB NVMe SSD' },
    display_order: 4,
  },
  {
    category: 'games',
    name: 'Titan',
    description: 'Heavy modpacks',
    price: '800',
    specs: { ram: '16GB DDR4 RAM', cpu: '350% CPU', ssd: '50GB NVMe SSD' },
    display_order: 5,
  },
  // VPS
  {
    category: 'vps',
    name: 'Basic',
    description: 'Small apps & testing',
    price: '150',
    specs: { ram: '2GB RAM', cpu: '1 vCore', ssd: '30GB SSD', bandwidth: '1TB Bandwidth' },
    display_order: 1,
  },
  {
    category: 'vps',
    name: 'Standard',
    description: 'Websites & moderate workloads',
    price: '250',
    specs: { ram: '4GB RAM', cpu: '2 vCore', ssd: '30GB SSD', bandwidth: '2TB Bandwidth' },
    display_order: 2,
  },
  {
    category: 'vps',
    name: 'Advanced',
    description: 'Growing projects',
    price: '400',
    specs: { ram: '8GB RAM', cpu: '3 vCore', ssd: '50GB SSD', bandwidth: '3TB Bandwidth' },
    featured: true,
    badge: 'MOST POPULAR',
    display_order: 3,
  },
  {
    category: 'vps',
    name: 'Pro',
    description: 'Production workloads',
    price: '600',
    specs: { ram: '16GB RAM', cpu: '4 vCore', ssd: '100GB SSD', bandwidth: '5TB Bandwidth' },
    display_order: 4,
  },
  // Web
  {
    category: 'web',
    name: 'Starter Web',
    description: 'Small sites',
    price: '100',
    specs: { ram: '4GB RAM', ssd: '30GB Disk', ssl: 'Free SSL', panel: 'cPanel', bandwidth: 'Unmetered' },
    display_order: 1,
  },
  {
    category: 'web',
    name: 'Pro Web',
    description: 'Growing sites',
    price: '200',
    specs: { ram: '8GB RAM', ssd: '50GB Disk', ssl: 'Free SSL', panel: 'cPanel', bandwidth: 'Unmetered' },
    featured: true,
    badge: 'MOST POPULAR',
    display_order: 2,
  },
  // VDS
  {
    category: 'vds',
    name: 'Standard VDS',
    description: 'Dedicated resources',
    price: '1500',
    specs: { ram: '8GB DDR4', cpu: '2 Dedicated Cores', ssd: '100GB NVMe', bandwidth: '10TB Bandwidth' },
    display_order: 1,
  },
  {
    category: 'vds',
    name: 'Pro VDS',
    description: 'Enterprise power',
    price: '3000',
    specs: { ram: '16GB DDR4', cpu: '4 Dedicated Cores', ssd: '200GB NVMe', bandwidth: '20TB Bandwidth' },
    featured: true,
    badge: 'BEST VALUE',
    display_order: 2,
  },
  // Bots
  {
    category: 'bots',
    name: 'Mini Bot',
    description: 'Small discord bots',
    price: '99',
    specs: { ram: '1GB RAM', cpu: '50% CPU', ssd: '5GB NVMe', backup: 'Daily Backups' },
    display_order: 1,
  },
  {
    category: 'bots',
    name: 'Standard Bot',
    description: 'Production bots',
    price: '199',
    specs: { ram: '2GB RAM', cpu: '100% CPU', ssd: '10GB NVMe', backup: 'Daily Backups' },
    featured: true,
    badge: 'MOST POPULAR',
    display_order: 2,
  },
];
