'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'hi' | 'es' | 'fr' | 'de' | 'it' | 'pt' | 'ru' | 'zh' | 'ja';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.games': 'Games',
    'nav.vps': 'VPS',
    'nav.web': 'Web',
    'nav.bots': 'Bots',
    'nav.reseller': 'Reseller',
    'nav.partnership': 'Partnership',
    'nav.services': 'Services',
    'nav.partners': 'Partners',
    'nav.company': 'Company',
    'nav.login': 'Login',
    'nav.about': 'About Us',
    'nav.contact': 'Contact',
    'nav.pricing': 'Pricings',
    'nav.calculator': 'Calculator',
    'nav.gameServersDesc': 'Lag-free gaming templates',
    'nav.webHostingDesc': 'Fast cPanel web hosting',
    'nav.vpsHostingDesc': 'Scalable cloud servers',
    'nav.vdsHostingDesc': 'Dedicated resources',
    'nav.botHostingDesc': '24/7 Discord & more',
    'nav.resellerDesc': 'Start your own brand',
    'nav.partnershipDesc': 'Grow with ZEROX',
    'nav.calculatorDesc': 'Estimate your costs',
    'nav.pricingDesc': 'All hosting plans',
    'nav.aboutDesc': 'Our infrastructure',
    'nav.contactDesc': '24/7 Discord support',
    'nav.aup': 'AUP',
    'nav.sla': 'SLA',
    'nav.legal': 'Legal',

    'hero.badge': 'Game Hosting',
    'hero.title': 'Host your own',
    'hero.subtitle': 'Game Servers',
    'hero.desc': 'Experience lightning-fast performance, unbeatable reliability, and 24/7 support for all your favorite games.',
    'hero.pill1': 'Game servers',
    'hero.pill2': 'Cloud VPS',
    'hero.pill3': 'Discord bots',
    'hero.pill4': 'Special deals',
    'hero.getStarted': 'Get started',
    'hero.learnMore': 'Learn More',
    'hero.uptime': 'Uptime',
    'hero.protection': 'Protection',
    'hero.hardware': 'Hardware',
    'hero.featuredBadge': 'Now featuring',
    'hero.from': 'from',
    'hero.perPlan': '/plan',
    'hero.deployServer': 'Deploy server',
    'hero.card1Title': 'Games',
    'hero.card1Desc': 'High-tick servers',
    'hero.card2Title': 'Cloud',
    'hero.card2Desc': 'Scalable nodes',

    'common.getStarted': 'Get Started',
    'common.learnMore': 'Learn More',
    'common.buyNow': 'Buy Now',
    'pricing.title': 'Pick your',
    'pricing.subtitle': 'entry plan',
    // Reseller
    'reseller.category': 'Reseller Program',
    'reseller.title': 'Start Your Own',
    'reseller.subtitle': 'Hosting Business',
    'reseller.desc': 'Become a partner and leverage our enterprise-grade infrastructure to launch your own hosting brand with zero upfront hardware costs.',
    // Partnership
    'partnership.category': 'Strategic Partnerships',
    'partnership.title': 'Growing Together',
    'partnership.subtitle': 'Partner with ZEROX',
    'partnership.desc': 'We collaborate with influencers, developers, and communities to build the next generation of digital infrastructure.',
    'partnership.whyTitle': 'Why Partner',
    'partnership.whyWithUs': 'With Us?',
    'partnership.formTitle': 'Inquiry Form',
    'partnership.formName': 'Full Name',
    'partnership.formEmail': 'Email Address',
    'partnership.formProject': 'Project/Community',
    'partnership.formMessage': 'Message',
    'partnership.formSubmit': 'Send Proposal',
    // Topics
    'games.title': 'Premium Game',
    'games.subtitle': 'Hosting Solutions',
    'vps.title': 'High Performance',
    'vps.subtitle': 'Cloud VPS',
    'web.title': 'Ultra-Fast Web',
    'web.subtitle': 'Hosting Services',
    'bots.title': 'Reliable Bot',
    'bots.subtitle': 'Hosting nodes',
  },
  hi: {
    'nav.home': 'मुख्य',
    'nav.games': 'गेम्स',
    'nav.vps': 'वीपीएस',
    'nav.web': 'वेब',
    'nav.bots': 'बॉट्स',
    'nav.reseller': 'रिसेलर',
    'nav.partnership': 'साझेदारी',
    'nav.services': 'सेवाएं',
    'nav.partners': 'भागीदार',
    'nav.company': 'कंपनी',
    'nav.login': 'लॉगिन',
    'nav.about': 'हमारे बारे में',
    'nav.contact': 'संपर्क करें',
    'nav.pricing': 'कीमतें',
    'nav.calculator': 'कैलकुलेटर',
    'nav.gameServersDesc': 'लैग-फ्री गेमिंग टेम्पलेट्स',
    'nav.webHostingDesc': 'तेज़ cPanel वेब होस्टिंग',
    'nav.vpsHostingDesc': 'स्केलेबल क्लाउड सर्वर',
    'nav.vdsHostingDesc': 'समर्पित संसाधन',
    'nav.botHostingDesc': '24/7 डिस्कॉर्ड और बहुत कुछ',
    'nav.resellerDesc': 'अपना खुद का ब्रांड शुरू करें',
    'nav.partnershipDesc': 'ZEROX के साथ बढ़ें',
    'nav.calculatorDesc': 'अपनी लागत का अनुमान लगाएं',
    'nav.pricingDesc': 'सभी होस्टिंग प्लान',
    'nav.aboutDesc': 'हमारा बुनियादी ढांचा',
    'nav.contactDesc': '24/7 डिस्कॉर्ड सहायता',
    'nav.aup': 'AUP',
    'nav.sla': 'SLA',
    'nav.legal': 'कानूनी',

    'hero.badge': 'गेम होस्टिंग',
    'hero.title': 'होस्ट करें अपना',
    'hero.subtitle': 'गेम सर्वर',
    'hero.desc': 'बिजली जैसी तेज गति, अटूट विश्वसनीयता और अपने सभी पसंदीदा खेलों के लिए 24/7 सहायता का अनुभव करें।',
    'hero.pill1': 'गेम सर्वर',
    'hero.pill2': 'क्लाउड वीपीएस',
    'hero.pill3': 'डिस्कॉर्ड बॉट्स',
    'hero.pill4': 'विशेष सौदे',
    'hero.getStarted': 'शुरू करें',
    'hero.learnMore': 'और जानें',
    'hero.uptime': 'अपटाइम',
    'hero.protection': 'सुरक्षा',
    'hero.hardware': 'हार्डवेयर',
    'hero.featuredBadge': 'अब उपलब्ध',
    'hero.from': 'से',
    'hero.perPlan': '/प्लान',
    'hero.deployServer': 'सर्वर तैनात करें',
    'hero.card1Title': 'गेम्स',
    'hero.card1Desc': 'हाई-टिक सर्वर',
    'hero.card2Title': 'क्लाउड',
    'hero.card2Desc': 'स्केलेबल नोड्स',

    'common.getStarted': 'शुरू करें',
    'common.learnMore': 'और जानें',
    'common.buyNow': 'अभी खरीदें',
    'pricing.title': 'अपना',
    'pricing.subtitle': 'प्लान चुनें',
    // Reseller
    'reseller.category': 'रिसेलर प्रोग्राम',
    'reseller.title': 'अपना खुद का',
    'reseller.subtitle': 'होस्टिंग व्यवसाय शुरू करें',
    'reseller.desc': 'एक भागीदार बनें और शून्य अग्रिम हार्डवेयर लागत के साथ अपना खुद का होस्टिंग ब्रांड लॉन्च करने के लिए हमारे एंटरप्राइज़-ग्रेड बुनियादी ढांचे का लाभ उठाएं।',
    // Partnership
    'partnership.category': 'रणनीतिक साझेदारी',
    'partnership.title': 'साथ में बढ़ रहे हैं',
    'partnership.subtitle': 'ZEROX के साथ पार्टनर बनें',
    'partnership.desc': 'हम अगली पीढ़ी के डिजिटल बुनियादी ढांचे के निर्माण के लिए प्रभावशाली लोगों, डेवलपर्स और समुदायों के साथ सहयोग करते हैं।',
    'partnership.whyTitle': 'पार्टनर क्यों',
    'partnership.whyWithUs': 'हमारे साथ?',
    'partnership.formTitle': 'पूछताछ फॉर्म',
    'partnership.formName': 'पूरा नाम',
    'partnership.formEmail': 'ईमेल पता',
    'partnership.formProject': 'परियोजना/समुदाय',
    'partnership.formMessage': 'संदेश',
    'partnership.formSubmit': 'प्रस्ताव भेजें',
    // Topics
    'games.title': 'प्रीमियम गेम',
    'games.subtitle': 'होस्टिंग समाधान',
    'vps.title': 'उच्च प्रदर्शन',
    'vps.subtitle': 'क्लाउड वीपीएस',
    'web.title': 'अति-तेज वेब',
    'web.subtitle': 'होस्टिंग सेवाएं',
    'bots.title': 'विश्वसनीय बॉट',
    'bots.subtitle': 'होस्टिंग नोड्स',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.games': 'Juegos',
    'nav.vps': 'VPS',
    'nav.web': 'Web',
    'nav.bots': 'Bots',
    'nav.reseller': 'Revendedor',
    'nav.partnership': 'Asociación',
    'nav.services': 'Servicios',
    'nav.partners': 'Socios',
    'nav.company': 'Compañía',
    'nav.login': 'Acceso',
    'nav.about': 'Nosotros',
    'nav.contact': 'Contacto',
    'nav.pricing': 'Precios',
    'nav.calculator': 'Calculadora',
    'nav.gameServersDesc': 'Plantillas de juego sin lag',
    'nav.webHostingDesc': 'Hosting web cPanel rápido',
    'nav.vpsHostingDesc': 'Servidores nube escalables',
    'nav.vdsHostingDesc': 'Recursos dedicados',
    'nav.botHostingDesc': '24/7 Discord y más',
    'nav.resellerDesc': 'Crea tu propia marca',
    'nav.partnershipDesc': 'Crece con ZEROX',
    'nav.calculatorDesc': 'Estima tus costos',
    'nav.pricingDesc': 'Todos los planes',
    'nav.aboutDesc': 'Nuestra infraestructura',
    'nav.contactDesc': 'Soporte Discord 24/7',
    'nav.aup': 'AUP',
    'nav.sla': 'SLA',
    'nav.legal': 'Legal',

    'hero.badge': 'Hosting de Juegos',
    'hero.title': 'Aloja tus propios',
    'hero.subtitle': 'Servidores de Juegos',
    'hero.desc': 'Experimente un rendimiento ultrarrápido, una confiabilidad inmejorable y soporte 24/7 para todos sus juegos favoritos.',
    'hero.pill1': 'Servidores de juegos',
    'hero.pill2': 'Cloud VPS',
    'hero.pill3': 'Bots de Discord',
    'hero.pill4': 'Ofertas especiales',
    'hero.getStarted': 'Empezar',
    'hero.learnMore': 'Saber más',
    'hero.uptime': 'Uptime',
    'hero.protection': 'Protección',
    'hero.hardware': 'Hardware',
    'hero.featuredBadge': 'Ahora destacando',
    'hero.from': 'desde',
    'hero.perPlan': '/plan',
    'hero.deployServer': 'Desplegar servidor',
    'hero.card1Title': 'Juegos',
    'hero.card1Desc': 'Servidores alto tick',
    'hero.card2Title': 'Nube',
    'hero.card2Desc': 'Nodos escalables',

    'common.getStarted': 'Empezar',
    'common.learnMore': 'Saber más',
    'common.buyNow': 'Comprar ahora',
    'pricing.title': 'Elige tu',
    'pricing.subtitle': 'plan de entrada',
    // Reseller
    'reseller.category': 'Programa de Revendedores',
    'reseller.title': 'Inicia Tu Propio',
    'reseller.subtitle': 'Negocio de Hosting',
    'reseller.desc': 'Conviértase en socio y aproveche nuestra infraestructura de nivel empresarial para lanzar su propia marca de hosting sin costos iniciales de hardware.',
    // Partnership
    'partnership.category': 'Asociaciones Estratégicas',
    'partnership.title': 'Creciendo Juntos',
    'partnership.subtitle': 'Asóciese con ZEROX',
    'partnership.desc': 'Colaboramos con influencers, desarrolladores y comunidades para construir la próxima generación de infraestructura digital.',
    'partnership.whyTitle': '¿Por qué asociarse',
    'partnership.whyWithUs': 'con nosotros?',
    'partnership.formTitle': 'Formulario de consulta',
    'partnership.formName': 'Nombre completo',
    'partnership.formEmail': 'Correo electrónico',
    'partnership.formProject': 'Proyecto/Comunidad',
    'partnership.formMessage': 'Mensaje',
    'partnership.formSubmit': 'Enviar propuesta',
    // Topics
    'games.title': 'Juego Premium',
    'games.subtitle': 'Soluciones de Hosting',
    'vps.title': 'Alto Rendimiento',
    'vps.subtitle': 'Cloud VPS',
    'web.title': 'Web Ultrarrápido',
    'web.subtitle': 'Servicios de Hosting',
    'bots.title': 'Bot Confiable',
    'bots.subtitle': 'Nodos de Hosting',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.games': 'Jeux',
    'nav.vps': 'VPS',
    'nav.web': 'Web',
    'nav.bots': 'Bots',
    'nav.reseller': 'Revendeur',
    'nav.partnership': 'Partenariat',
    'nav.services': 'Services',
    'nav.partners': 'Partenaires',
    'nav.company': 'Entreprise',
    'nav.login': 'Connexion',
    'nav.about': 'À propos',
    'nav.contact': 'Contact',
    'nav.pricing': 'Tarifs',
    'nav.calculator': 'Calculateur',
    'nav.gameServersDesc': 'Modèles de jeux sans lag',
    'nav.webHostingDesc': 'Hébergement web cPanel rapide',
    'nav.vpsHostingDesc': 'Serveurs cloud évolutifs',
    'nav.vdsHostingDesc': 'Ressources dédiées',
    'nav.botHostingDesc': '24/7 Discord et plus',
    'nav.resellerDesc': 'Lancez votre propre marque',
    'nav.partnershipDesc': 'Grandissez avec ZEROX',
    'nav.calculatorDesc': 'Estimez vos coûts',
    'nav.pricingDesc': 'Tous les plans',
    'nav.aboutDesc': 'Notre infrastructure',
    'nav.contactDesc': 'Support Discord 24/7',
    'nav.aup': 'AUP',
    'nav.sla': 'SLA',
    'nav.legal': 'Juridique',

    'hero.badge': 'Hébergement de Jeux',
    'hero.title': 'Hébergez vos propres',
    'hero.subtitle': 'Serveurs de Jeux',
    'hero.desc': 'Découvrez des performances ultra-rapides, une fiabilité inégalée et une assistance 24h/24 et 7j/7 pour tous vos jeux préférés.',
    'hero.pill1': 'Serveurs de jeux',
    'hero.pill2': 'Cloud VPS',
    'hero.pill3': 'Bots Discord',
    'hero.pill4': 'Offres spéciales',
    'hero.getStarted': 'Commencer',
    'hero.learnMore': 'En savoir plus',
    'hero.uptime': 'Disponibilité',
    'hero.protection': 'Protection',
    'hero.hardware': 'Matériel',
    'hero.featuredBadge': 'En vedette',
    'hero.from': 'à partir de',
    'hero.perPlan': '/plan',
    'hero.deployServer': 'Déployer serveur',
    'hero.card1Title': 'Jeux',
    'hero.card1Desc': 'Serveurs haut tick',
    'hero.card2Title': 'Cloud',
    'hero.card2Desc': 'Noeuds évolutifs',

    'common.getStarted': 'Commencer',
    'common.learnMore': 'En savoir plus',
    'common.buyNow': 'Acheter maintenant',
    'pricing.title': 'Choisissez votre',
    'pricing.subtitle': 'plan d\'entrée',
    // Reseller
    'reseller.category': 'Programme de Revendeur',
    'reseller.title': 'Lancez Votre Propre',
    'reseller.subtitle': 'Entreprise d\'Hébergement',
    'reseller.desc': 'Devenez partenaire et tirez parti de notre infrastructure de classe entreprise pour lancer votre propre marque d\'hébergement sans frais de matériel initiaux.',
    // Partnership
    'partnership.category': 'Partenariats Stratégiques',
    'partnership.title': 'Grandir Ensemble',
    'partnership.subtitle': 'Partenaire de ZEROX',
    'partnership.desc': 'Nous collaborons avec des influenceurs, des développeurs et des communautés pour construire la prochaine génération d\'infrastructure numérique.',
    'partnership.whyTitle': 'Pourquoi s\'associer',
    'partnership.whyWithUs': 'avec nous ?',
    'partnership.formTitle': 'Formulaire de demande',
    'partnership.formName': 'Nom complet',
    'partnership.formEmail': 'Adresse e-mail',
    'partnership.formProject': 'Projet/Communauté',
    'partnership.formMessage': 'Message',
    'partnership.formSubmit': 'Envoyer la proposition',
    // Topics
    'games.title': 'Jeu Premium',
    'games.subtitle': 'Solutions d\'Hébergement',
    'vps.title': 'Haute Performance',
    'vps.subtitle': 'Cloud VPS',
    'web.title': 'Web Ultra-Rapide',
    'web.subtitle': 'Services d\'Hébergement',
    'bots.title': 'Bot Fiable',
    'bots.subtitle': 'Noeuds d\'Hébergement',
  },
  de: {
    'nav.home': 'Startseite',
    'nav.games': 'Spiele',
    'nav.vps': 'VPS',
    'nav.web': 'Web',
    'nav.bots': 'Bots',
    'nav.reseller': 'Reseller',
    'nav.partnership': 'Partnerschaft',
    'nav.services': 'Dienste',
    'nav.partners': 'Partner',
    'nav.company': 'Unternehmen',
    'nav.login': 'Login',
    'nav.about': 'Über uns',
    'nav.contact': 'Kontakt',
    'nav.pricing': 'Preise',
    'nav.calculator': 'Rechner',
    'nav.gameServersDesc': 'Lag-freie Spielvorlagen',
    'nav.webHostingDesc': 'Schnelles cPanel Webhosting',
    'nav.vpsHostingDesc': 'Skalierbare Cloud-Server',
    'nav.vdsHostingDesc': 'Dedizierte Ressourcen',
    'nav.botHostingDesc': '24/7 Discord & mehr',
    'nav.resellerDesc': 'Eigene Marke starten',
    'nav.partnershipDesc': 'Wachsen mit ZEROX',
    'nav.calculatorDesc': 'Kosten schätzen',
    'nav.pricingDesc': 'Alle Hosting-Pläne',
    'nav.aboutDesc': 'Unsere Infrastruktur',
    'nav.contactDesc': '24/7 Discord-Support',
    'nav.aup': 'AUP',
    'nav.sla': 'SLA',
    'nav.legal': 'Rechtliches',

    'hero.badge': 'Game-Hosting',
    'hero.title': 'Hoste deine eigenen',
    'hero.subtitle': 'Game-Server',
    'hero.desc': 'Erlebe blitzschnelle Performance, unschlagbare Zuverlässigkeit und 24/7 Support für alle deine Lieblingsspiele.',
    'hero.pill1': 'Game-Server',
    'hero.pill2': 'Cloud VPS',
    'hero.pill3': 'Discord-Bots',
    'hero.pill4': 'Sonderangebote',
    'hero.getStarted': 'Jetzt starten',
    'hero.learnMore': 'Mehr erfahren',
    'hero.uptime': 'Uptime',
    'hero.protection': 'Schutz',
    'hero.hardware': 'Hardware',
    'hero.featuredBadge': 'Jetzt neu',
    'hero.from': 'ab',
    'hero.perPlan': '/Plan',
    'hero.deployServer': 'Server bereitstellen',
    'hero.card1Title': 'Spiele',
    'hero.card1Desc': 'High-Tick-Server',
    'hero.card2Title': 'Cloud',
    'hero.card2Desc': 'Skalierbare Knoten',

    'common.getStarted': 'Jetzt starten',
    'common.learnMore': 'Mehr erfahren',
    'common.buyNow': 'Jetzt kaufen',
    'pricing.title': 'Wähle deinen',
    'pricing.subtitle': 'Einstiegsplan',
    // Reseller
    'reseller.category': 'Reseller-Programm',
    'reseller.title': 'Starte dein eigenes',
    'reseller.subtitle': 'Hosting-Business',
    'reseller.desc': 'Werde Partner und nutze unsere Enterprise-Infrastruktur, um deine eigene Hosting-Marke ohne Hardware-Vorkosten zu starten.',
    // Partnership
    'partnership.category': 'Strategische Partnerschaften',
    'partnership.title': 'Gemeinsam wachsen',
    'partnership.subtitle': 'Partner von ZEROX werden',
    'partnership.desc': 'Wir arbeiten mit Influencern, Entwicklern und Communities zusammen, um die nächste Generation digitaler Infrastruktur aufzubauen.',
    'partnership.whyTitle': 'Warum Partner',
    'partnership.whyWithUs': 'werden?',
    'partnership.formTitle': 'Anfrageformular',
    'partnership.formName': 'Vollständiger Name',
    'partnership.formEmail': 'E-Mail-Adresse',
    'partnership.formProject': 'Projekt/Community',
    'partnership.formMessage': 'Nachricht',
    'partnership.formSubmit': 'Vorschlag senden',
    // Topics
    'games.title': 'Premium Game',
    'games.subtitle': 'Hosting-Lösungen',
    'vps.title': 'High Performance',
    'vps.subtitle': 'Cloud VPS',
    'web.title': 'Ultra-Schnelles Web',
    'web.subtitle': 'Hosting-Dienste',
    'bots.title': 'Zuverlässiges Bot',
    'bots.subtitle': 'Hosting-Knoten',
  },
  it: {
    'nav.home': 'Home',
    'nav.games': 'Giochi',
    'nav.vps': 'VPS',
    'nav.web': 'Web',
    'nav.bots': 'Bot',
    'nav.reseller': 'Rivenditore',
    'nav.partnership': 'Partnership',
    'nav.services': 'Servizi',
    'nav.partners': 'Partner',
    'nav.company': 'Azienda',
    'nav.login': 'Login',
    'nav.about': 'Chi siamo',
    'nav.contact': 'Contatti',
    'nav.pricing': 'Prezzi',
    'nav.calculator': 'Calcolatore',
    'nav.gameServersDesc': 'Template di gioco senza lag',
    'nav.webHostingDesc': 'Web hosting cPanel veloce',
    'nav.vpsHostingDesc': 'Server cloud scalabili',
    'nav.vdsHostingDesc': 'Risorse dedicate',
    'nav.botHostingDesc': '24/7 Discord e altro',
    'nav.resellerDesc': 'Avvia il tuo marchio',
    'nav.partnershipDesc': 'Cresci con ZEROX',
    'nav.calculatorDesc': 'Stima i tuoi costi',
    'nav.pricingDesc': 'Tutti i piani hosting',
    'nav.aboutDesc': 'La nostra infrastruttura',
    'nav.contactDesc': 'Supporto Discord 24/7',
    'nav.aup': 'AUP',
    'nav.sla': 'SLA',
    'nav.legal': 'Legale',

    'hero.badge': 'Hosting Giochi',
    'hero.title': 'Ospita i tuoi',
    'hero.subtitle': 'Server di Gioco',
    'hero.desc': 'Sperimenta prestazioni fulminee, affidabilità imbattibile e supporto 24/7 per tutti i tuoi giochi preferiti.',
    'hero.pill1': 'Server di gioco',
    'hero.pill2': 'Cloud VPS',
    'hero.pill3': 'Bot Discord',
    'hero.pill4': 'Offerte speciali',
    'hero.getStarted': 'Inizia ora',
    'hero.learnMore': 'Scopri di più',
    'hero.uptime': 'Uptime',
    'hero.protection': 'Protezione',
    'hero.hardware': 'Hardware',
    'hero.featuredBadge': 'In evidenza',
    'hero.from': 'da',
    'hero.perPlan': '/piano',
    'hero.deployServer': 'Distribuisci server',
    'hero.card1Title': 'Giochi',
    'hero.card1Desc': 'Server high-tick',
    'hero.card2Title': 'Cloud',
    'hero.card2Desc': 'Nodi scalabili',

    'common.getStarted': 'Inizia ora',
    'common.learnMore': 'Scopri di più',
    'common.buyNow': 'Acquista ora',
    'pricing.title': 'Scegli il tuo',
    'pricing.subtitle': 'piano d\'ingresso',
    // Reseller
    'reseller.category': 'Programma Rivenditori',
    'reseller.title': 'Avvia la Tua',
    'reseller.subtitle': 'Attività di Hosting',
    'reseller.desc': 'Diventa partner e sfrutta la nostra infrastruttura enterprise per lanciare il tuo marchio di hosting senza costi hardware iniziali.',
    // Partnership
    'partnership.category': 'Partnership Strategiche',
    'partnership.title': 'Crescere Insieme',
    'partnership.subtitle': 'Diventa partner ZEROX',
    'partnership.desc': 'Collaboriamo con influencer, sviluppatori e community per costruire la prossima generazione di infrastruttura digitale.',
    'partnership.whyTitle': 'Perché diventare',
    'partnership.whyWithUs': 'partner?',
    'partnership.formTitle': 'Modulo di richiesta',
    'partnership.formName': 'Nome completo',
    'partnership.formEmail': 'Indirizzo e-mail',
    'partnership.formProject': 'Progetto/Community',
    'partnership.formMessage': 'Messaggio',
    'partnership.formSubmit': 'Invia proposta',
    // Topics
    'games.title': 'Gioco Premium',
    'games.subtitle': 'Soluzioni Hosting',
    'vps.title': 'Alte Prestazioni',
    'vps.subtitle': 'Cloud VPS',
    'web.title': 'Web Ultra-Veloce',
    'web.subtitle': 'Servizi Hosting',
    'bots.title': 'Bot Affidabile',
    'bots.subtitle': 'Nodi Hosting',
  },
  pt: {
    'nav.home': 'Início',
    'nav.games': 'Jogos',
    'nav.vps': 'VPS',
    'nav.web': 'Web',
    'nav.bots': 'Bots',
    'nav.reseller': 'Revenda',
    'nav.partnership': 'Parceria',
    'nav.services': 'Serviços',
    'nav.partners': 'Parceiros',
    'nav.company': 'Empresa',
    'nav.login': 'Login',
    'nav.about': 'Sobre',
    'nav.contact': 'Contato',
    'nav.pricing': 'Preços',
    'nav.calculator': 'Calculadora',
    'nav.gameServersDesc': 'Templates de jogos sem lag',
    'nav.webHostingDesc': 'Hospedagem web cPanel rápida',
    'nav.vpsHostingDesc': 'Servidores cloud escaláveis',
    'nav.vdsHostingDesc': 'Recursos dedicados',
    'nav.botHostingDesc': '24/7 Discord e mais',
    'nav.resellerDesc': 'Crie sua própria marca',
    'nav.partnershipDesc': 'Cresça com a ZEROX',
    'nav.calculatorDesc': 'Estime seus custos',
    'nav.pricingDesc': 'Todos os planos',
    'nav.aboutDesc': 'Nossa infraestrutura',
    'nav.contactDesc': 'Suporte Discord 24/7',
    'nav.aup': 'AUP',
    'nav.sla': 'SLA',
    'nav.legal': 'Legal',

    'hero.badge': 'Hospedagem de Jogos',
    'hero.title': 'Hospede seus próprios',
    'hero.subtitle': 'Servidores de Jogos',
    'hero.desc': 'Experimente desempenho ultrarrápido, confiabilidade imbatível e suporte 24/7 para todos os seus jogos favoritos.',
    'hero.pill1': 'Servidores de jogos',
    'hero.pill2': 'Cloud VPS',
    'hero.pill3': 'Bots de Discord',
    'hero.pill4': 'Ofertas especiais',
    'hero.getStarted': 'Começar',
    'hero.learnMore': 'Saiba mais',
    'hero.uptime': 'Uptime',
    'hero.protection': 'Proteção',
    'hero.hardware': 'Hardware',
    'hero.featuredBadge': 'Destaque agora',
    'hero.from': 'a partir de',
    'hero.perPlan': '/plano',
    'hero.deployServer': 'Implantar servidor',
    'hero.card1Title': 'Jogos',
    'hero.card1Desc': 'Servidores high-tick',
    'hero.card2Title': 'Nuvem',
    'hero.card2Desc': 'Nós escaláveis',

    'common.getStarted': 'Começar',
    'common.learnMore': 'Saiba mais',
    'common.buyNow': 'Comprar agora',
    'pricing.title': 'Escolha seu',
    'pricing.subtitle': 'plano de entrada',
    // Reseller
    'reseller.category': 'Programa de Revenda',
    'reseller.title': 'Inicie seu Próprio',
    'reseller.subtitle': 'Negócio de Hospedagem',
    'reseller.desc': 'Torne-se um parceiro e aproveite nossa infraestrutura empresarial para lançar sua própria marca de hospedagem sem custos iniciais de hardware.',
    // Partnership
    'partnership.category': 'Parcerias Estratégicas',
    'partnership.title': 'Crescendo Juntos',
    'partnership.subtitle': 'Seja parceiro da ZEROX',
    'partnership.desc': 'Colaboramos com influenciadores, desenvolvedores e comunidades para construir a próxima geração de infraestrutura digital.',
    'partnership.whyTitle': 'Por que ser',
    'partnership.whyWithUs': 'parceiro?',
    'partnership.formTitle': 'Formulário de Contato',
    'partnership.formName': 'Nome Completo',
    'partnership.formEmail': 'Endereço de E-mail',
    'partnership.formProject': 'Projeto/Comunidade',
    'partnership.formMessage': 'Mensagem',
    'partnership.formSubmit': 'Enviar Proposta',
    // Topics
    'games.title': 'Jogo Premium',
    'games.subtitle': 'Soluções de Hospedagem',
    'vps.title': 'Alta Performance',
    'vps.subtitle': 'Cloud VPS',
    'web.title': 'Web Ultra-Rápida',
    'web.subtitle': 'Serviços de Hospedagem',
    'bots.title': 'Bot Confiável',
    'bots.subtitle': 'Nós de Hospedagem',
  },
  ru: {
    'nav.home': 'Главная',
    'nav.games': 'Игры',
    'nav.vps': 'VPS',
    'nav.web': 'Веб',
    'nav.bots': 'Боты',
    'nav.reseller': 'Реселлерам',
    'nav.partnership': 'Партнерство',
    'nav.services': 'Услуги',
    'nav.partners': 'Партнеры',
    'nav.company': 'Компания',
    'nav.login': 'Вход',
    'nav.about': 'О нас',
    'nav.contact': 'Контакты',
    'nav.pricing': 'Цены',
    'nav.calculator': 'Калькулятор',
    'nav.gameServersDesc': 'Игровые шаблоны без лагов',
    'nav.webHostingDesc': 'Быстрый cPanel веб-хостинг',
    'nav.vpsHostingDesc': 'Масштабируемые облачные серверы',
    'nav.vdsHostingDesc': 'Выделенные ресурсы',
    'nav.botHostingDesc': '24/7 Discord и др.',
    'nav.resellerDesc': 'Запустите свой бренд',
    'nav.partnershipDesc': 'Растите вместе с ZEROX',
    'nav.calculatorDesc': 'Оцените расходы',
    'nav.pricingDesc': 'Все тарифные планы',
    'nav.aboutDesc': 'Наша инфраструктура',
    'nav.contactDesc': 'Поддержка в Discord 24/7',
    'nav.aup': 'AUP',
    'nav.sla': 'SLA',
    'nav.legal': 'Юридическая',

    'hero.badge': 'Игровой хостинг',
    'hero.title': 'Создайте свой',
    'hero.subtitle': 'Игровой сервер',
    'hero.desc': 'Ощутите молниеносную производительность, непревзойденную надежность и круглосуточную поддержку для всех ваших любимых игр.',
    'hero.pill1': 'Игровые серверы',
    'hero.pill2': 'Облачные VPS',
    'hero.pill3': 'Discord боты',
    'hero.pill4': 'Спецпредложения',
    'hero.getStarted': 'Начать',
    'hero.learnMore': 'Подробнее',
    'hero.uptime': 'Аптайм',
    'hero.protection': 'Защита',
    'hero.hardware': 'Железо',
    'hero.featuredBadge': 'Сейчас в топе',
    'hero.from': 'от',
    'hero.perPlan': '/план',
    'hero.deployServer': 'Запустить сервер',
    'hero.card1Title': 'Игры',
    'hero.card1Desc': 'Высокочастотные серверы',
    'hero.card2Title': 'Облако',
    'hero.card2Desc': 'Масштабируемые узлы',

    'common.getStarted': 'Начать',
    'common.learnMore': 'Подробнее',
    'common.buyNow': 'Купить сейчас',
    'pricing.title': 'Выберите свой',
    'pricing.subtitle': 'начальный план',
    // Reseller
    'reseller.category': 'Реселлерская программа',
    'reseller.title': 'Начните свой',
    'reseller.subtitle': 'Хостинг-бизнес',
    'reseller.desc': 'Станьте партнером и используйте нашу корпоративную инфраструктуру для запуска собственного хостинг-бренда без затрат на оборудование.',
    // Partnership
    'partnership.category': 'Стратегическое партнерство',
    'partnership.title': 'Растем вместе',
    'partnership.subtitle': 'Станьте партнером ZEROX',
    'partnership.desc': 'Мы сотрудничаем с инфлюенсерами, разработчиками и сообществами для создания цифровой инфраструктуры будущего.',
    'partnership.whyTitle': 'Почему стоит',
    'partnership.whyWithUs': 'стать партнером?',
    'partnership.formTitle': 'Форма заявки',
    'partnership.formName': 'Полное имя',
    'partnership.formEmail': 'Email адрес',
    'partnership.formProject': 'Проект/Сообщество',
    'partnership.formMessage': 'Сообщение',
    'partnership.formSubmit': 'Отправить предложение',
    // Topics
    'games.title': 'Премиум Игры',
    'games.subtitle': 'Хостинг решения',
    'vps.title': 'Высокая производительность',
    'vps.subtitle': 'Облачные VPS',
    'web.title': 'Ультра-быстрый Веб',
    'web.subtitle': 'Хостинг услуги',
    'bots.title': 'Надежные Боты',
    'bots.subtitle': 'Хостинг узлы',
  },
  zh: {
    'nav.home': '首页',
    'nav.games': '游戏',
    'nav.vps': 'VPS',
    'nav.web': '网页',
    'nav.bots': '机器人',
    'nav.reseller': '分销',
    'nav.partnership': '合作',
    'nav.services': '服务',
    'nav.partners': '合作伙伴',
    'nav.company': '公司',
    'nav.login': '登录',
    'nav.about': '关于我们',
    'nav.contact': '联系我们',
    'nav.pricing': '价格',
    'nav.calculator': '计算器',
    'nav.gameServersDesc': '无延迟游戏模板',
    'nav.webHostingDesc': '快速 cPanel 网页托管',
    'nav.vpsHostingDesc': '可扩展云服务器',
    'nav.vdsHostingDesc': '专用资源',
    'nav.botHostingDesc': '24/7 Discord 及更多',
    'nav.resellerDesc': '开启您的自有品牌',
    'nav.partnershipDesc': '与 ZEROX 共同成长',
    'nav.calculatorDesc': '估算您的成本',
    'nav.pricingDesc': '所有托管方案',
    'nav.aboutDesc': '我们的基础设施',
    'nav.contactDesc': '24/7 Discord 支持',
    'nav.aup': 'AUP',
    'nav.sla': 'SLA',
    'nav.legal': '法律',

    'hero.badge': '游戏托管',
    'hero.title': '托管您的自有',
    'hero.subtitle': '游戏服务器',
    'hero.desc': '体验极速性能、无与伦比的可靠性，以及为您喜爱的所有游戏提供 24/7 支持。',
    'hero.pill1': '游戏服务器',
    'hero.pill2': '云 VPS',
    'hero.pill3': 'Discord 机器人',
    'hero.pill4': '特别优惠',
    'hero.getStarted': '立即开始',
    'hero.learnMore': '了解更多',
    'hero.uptime': '在线率',
    'hero.protection': '防护',
    'hero.hardware': '硬件',
    'hero.featuredBadge': '当前特色',
    'hero.from': '起价',
    'hero.perPlan': '/方案',
    'hero.deployServer': '部署服务器',
    'hero.card1Title': '游戏',
    'hero.card1Desc': '高 tick 服务器',
    'hero.card2Title': '云端',
    'hero.card2Desc': '可扩展节点',

    'common.getStarted': '立即开始',
    'common.learnMore': '了解更多',
    'common.buyNow': '立即购买',
    'pricing.title': '选择您的',
    'pricing.subtitle': '入门方案',
    // Reseller
    'reseller.category': '分销计划',
    'reseller.title': '开启您的自有',
    'reseller.subtitle': '托管业务',
    'reseller.desc': '成为合作伙伴，利用我们的企业级基础设施开启您的自有托管品牌，无需前期硬件投入。',
    // Partnership
    'partnership.category': '战略合作',
    'partnership.title': '共同成长',
    'partnership.subtitle': '与 ZEROX 合作',
    'partnership.desc': '我们与影响力人士、开发者和社区合作，构建下一代数字基础设施。',
    'partnership.whyTitle': '为何选择',
    'partnership.whyWithUs': '与我们合作？',
    'partnership.formTitle': '咨询表单',
    'partnership.formName': '全名',
    'partnership.formEmail': '电子邮箱',
    'partnership.formProject': '项目/社区',
    'partnership.formMessage': '留言',
    'partnership.formSubmit': '发送提案',
    // Topics
    'games.title': '优质游戏',
    'games.subtitle': '托管解决方案',
    'vps.title': '高性能',
    'vps.subtitle': '云 VPS',
    'web.title': '极速网页',
    'web.subtitle': '托管服务',
    'bots.title': '可靠机器人',
    'bots.subtitle': '托管节点',
  },
  ja: {
    'nav.home': 'ホーム',
    'nav.games': 'ゲーム',
    'nav.vps': 'VPS',
    'nav.web': 'ウェブ',
    'nav.bots': 'ボット',
    'nav.reseller': 'リセラー',
    'nav.partnership': 'パートナーシップ',
    'nav.services': 'サービス',
    'nav.partners': 'パートナー',
    'nav.company': '会社',
    'nav.login': 'ログイン',
    'nav.about': '会社概要',
    'nav.contact': 'お問い合わせ',
    'nav.pricing': '料金',
    'nav.calculator': '計算機',
    'nav.gameServersDesc': 'ラグのないゲームテンプレート',
    'nav.webHostingDesc': '高速 cPanel ウェブホスティング',
    'nav.vpsHostingDesc': '拡張可能なクラウドサーバー',
    'nav.vdsHostingDesc': '専用リソース',
    'nav.botHostingDesc': '24/7 Discord など',
    'nav.resellerDesc': '自社ブランドを開始',
    'nav.partnershipDesc': 'ZEROXと共に成長',
    'nav.calculatorDesc': 'コストを見積もる',
    'nav.pricingDesc': 'すべてのホスティングプラン',
    'nav.aboutDesc': '当社のインフラ',
    'nav.contactDesc': '24/7 Discordサポート',
    'nav.aup': 'AUP',
    'nav.sla': 'SLA',
    'nav.legal': 'リーガル',

    'hero.badge': 'ゲームホスティング',
    'hero.title': '自分だけの',
    'hero.subtitle': 'ゲームサーバー',
    'hero.desc': 'お気に入りのすべてのゲームに対して、超高速のパフォーマンス、比類のない信頼性、および 24/7 サポートを体験してください。',
    'hero.pill1': 'ゲームサーバー',
    'hero.pill2': 'クラウド VPS',
    'hero.pill3': 'Discordボット',
    'hero.pill4': '特別セール',
    'hero.getStarted': '今すぐ開始',
    'hero.learnMore': '詳しく見る',
    'hero.uptime': '稼働率',
    'hero.protection': '保護',
    'hero.hardware': 'ハードウェア',
    'hero.featuredBadge': '注目の機能',
    'hero.from': 'から',
    'hero.perPlan': '/プラン',
    'hero.deployServer': 'サーバーをデプロイ',
    'hero.card1Title': 'ゲーム',
    'hero.card1Desc': '高チックサーバー',
    'hero.card2Title': 'クラウド',
    'hero.card2Desc': '拡張可能なノード',

    'common.getStarted': '今すぐ開始',
    'common.learnMore': '詳しく見る',
    'common.buyNow': '今すぐ購入',
    'pricing.title': '最適な',
    'pricing.subtitle': 'エントリープラン',
    // Reseller
    'reseller.category': 'リセラープログラム',
    'reseller.title': '自分だけの',
    'reseller.subtitle': 'ホスティング事業を開始',
    'reseller.desc': 'パートナーになり、当社のエンタープライズ級インフラを活用して、初期ハードウェアコストなしで独自のホスティングブランドを立ち上げましょう。',
    // Partnership
    'partnership.category': '戦略的パートナーシップ',
    'partnership.title': '共に成長する',
    'partnership.subtitle': 'ZEROXと提携する',
    'partnership.desc': '当社はインフルエンサー、開発者、コミュニティと協力して、次世代のデジタルインフラを構築しています。',
    'partnership.whyTitle': '提携する',
    'partnership.whyWithUs': '理由は？',
    'partnership.formTitle': 'お問い合わせフォーム',
    'partnership.formName': 'フルネーム',
    'partnership.formEmail': 'メールアドレス',
    'partnership.formProject': 'プロジェクト/コミュニティ',
    'partnership.formMessage': 'メッセージ',
    'partnership.formSubmit': '提案を送信',
    // Topics
    'games.title': 'プレミアムゲーム',
    'games.subtitle': 'ホスティングソリューション',
    'vps.title': '高性能',
    'vps.subtitle': 'クラウド VPS',
    'web.title': '超高速ウェブ',
    'web.subtitle': 'ホスティングサービス',
    'bots.title': '信頼性の高いボット',
    'bots.subtitle': 'ホスティングノード',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('zerox_language') as Language | null;
    if (saved && translations[saved]) {
      setLanguage(saved);
      return;
    }

    const browserLang = navigator.language.slice(0, 2) as Language;
    if (translations[browserLang]) {
      setLanguage(browserLang);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('zerox_language', language);
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
